# Generated by Django 2.1.5 on 2019-11-15 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Five',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='home', max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Career_Five',
            },
        ),
        migrations.CreateModel(
            name='Career_Four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='home', max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Career_Four',
            },
        ),
        migrations.CreateModel(
            name='Career_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='home', max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Career_One',
            },
        ),
        migrations.CreateModel(
            name='Career_Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='home', max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Career_Three',
            },
        ),
        migrations.CreateModel(
            name='Career_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='home', max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Career_Two',
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='careers')),
                ('Day', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Year', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Head',
            },
        ),
    ]
