# Generated by Django 2.1.5 on 2019-11-15 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error404',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Error404',
            },
        ),
        migrations.CreateModel(
            name='Error500',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Error500',
            },
        ),
    ]
