# Generated by Django 2.1.5 on 2019-11-15 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Small', models.CharField(max_length=20)),
                ('Title_Big', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Features_Services',
            },
        ),
        migrations.CreateModel(
            name='Service_Five',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favicon', models.ImageField(upload_to='services')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Service_Five',
            },
        ),
        migrations.CreateModel(
            name='Service_Four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favicon', models.ImageField(upload_to='services')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Service_Four',
            },
        ),
        migrations.CreateModel(
            name='Service_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favicon', models.ImageField(upload_to='services')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Service_One',
            },
        ),
        migrations.CreateModel(
            name='Service_Six',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favicon', models.ImageField(upload_to='services')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Service_Six',
            },
        ),
        migrations.CreateModel(
            name='Service_Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favicon', models.ImageField(upload_to='services')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Service_Three',
            },
        ),
        migrations.CreateModel(
            name='Service_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favicon', models.ImageField(upload_to='services')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Service_Two',
            },
        ),
        migrations.CreateModel(
            name='Splash_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Splash_One',
            },
        ),
        migrations.CreateModel(
            name='Splash_Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Splash_Three',
            },
        ),
        migrations.CreateModel(
            name='Splash_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Splash_Two',
            },
        ),
    ]
