# Generated by Django 2.1.5 on 2019-11-15 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(upload_to='icons')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Button', models.CharField(default='Read More', max_length=20)),
                ('Link', models.CharField(default='home', max_length=50)),
            ],
            options={
                'db_table': 'Brand_One',
            },
        ),
        migrations.CreateModel(
            name='Brand_Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(upload_to='icons')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Button', models.CharField(default='Read More', max_length=20)),
                ('Link', models.CharField(default='home', max_length=50)),
            ],
            options={
                'db_table': 'Brand_Three',
            },
        ),
        migrations.CreateModel(
            name='Brand_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(upload_to='icons')),
                ('Title', models.CharField(max_length=30)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Button', models.CharField(default='Read More', max_length=20)),
                ('Link', models.CharField(default='home', max_length=50)),
            ],
            options={
                'db_table': 'Brand_Two',
            },
        ),
        migrations.CreateModel(
            name='Carousel_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_line_one', models.CharField(max_length=80)),
                ('Title_line_two', models.CharField(max_length=80)),
                ('Content', models.CharField(max_length=30)),
                ('Button', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='home')),
            ],
            options={
                'db_table': 'Carousel_One',
            },
        ),
        migrations.CreateModel(
            name='Carousel_Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_line_one', models.CharField(max_length=80)),
                ('Title_line_two', models.CharField(max_length=80)),
                ('Content', models.CharField(max_length=30)),
                ('Button', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='home')),
            ],
            options={
                'db_table': 'Carousel_Three',
            },
        ),
        migrations.CreateModel(
            name='Carousel_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_line_one', models.CharField(max_length=80)),
                ('Title_line_two', models.CharField(max_length=80)),
                ('Content', models.CharField(max_length=30)),
                ('Button', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='home')),
            ],
            options={
                'db_table': 'Carousel_Two',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Small', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=60)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Picture', models.ImageField(upload_to='home')),
            ],
            options={
                'db_table': 'Discover',
            },
        ),
        migrations.CreateModel(
            name='Map_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Background_Image', models.ImageField(upload_to='home')),
                ('Title', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Map_Area',
            },
        ),
        migrations.CreateModel(
            name='Referee_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Profile_Pic', models.ImageField(upload_to='home')),
                ('Name', models.CharField(max_length=30)),
                ('Job_Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Referee_One',
            },
        ),
        migrations.CreateModel(
            name='Referee_Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Profile_Pic', models.ImageField(upload_to='home')),
                ('Name', models.CharField(max_length=30)),
                ('Job_Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Referee_Three',
            },
        ),
        migrations.CreateModel(
            name='Referee_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Profile_Pic', models.ImageField(upload_to='home')),
                ('Name', models.CharField(max_length=30)),
                ('Job_Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Referee_Two',
            },
        ),
        migrations.CreateModel(
            name='Surprise_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(upload_to='icons')),
                ('Small_Content', models.CharField(max_length=50)),
                ('Big_Content', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Surprise',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Small', models.CharField(max_length=50)),
                ('Title_Big', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Picture_One', models.ImageField(upload_to='home')),
                ('Picture_Two', models.ImageField(upload_to='home')),
                ('Picture_Three', models.ImageField(upload_to='home')),
                ('Picture_Four', models.ImageField(upload_to='home')),
                ('Bullet_One', models.CharField(max_length=25)),
                ('Bullet_Two', models.CharField(max_length=25)),
                ('Bullet_Three', models.CharField(max_length=25)),
                ('Bullet_Four', models.CharField(max_length=25)),
                ('Bullet_Five', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
    ]
