# Generated by Django 2.1.5 on 2019-11-15 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Small', models.CharField(max_length=50)),
                ('Title_Big', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Button_Icon', models.ImageField(upload_to='icons')),
                ('Youtube_Link', models.CharField(max_length=150)),
                ('Picture', models.ImageField(upload_to='about')),
                ('Button', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'About',
            },
        ),
        migrations.CreateModel(
            name='Features_About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Small', models.CharField(max_length=50)),
                ('Title_Big', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Skills', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'Features_About',
            },
        ),
        migrations.CreateModel(
            name='Shoutout_Four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Picture', models.ImageField(upload_to='about')),
                ('Name', models.CharField(max_length=50)),
                ('Job_Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Shoutout_Four',
            },
        ),
        migrations.CreateModel(
            name='Shoutout_One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Picture', models.ImageField(upload_to='about')),
                ('Name', models.CharField(max_length=50)),
                ('Job_Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Shoutout_One',
            },
        ),
        migrations.CreateModel(
            name='Shoutout_Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Picture', models.ImageField(upload_to='about')),
                ('Name', models.CharField(max_length=50)),
                ('Job_Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Shoutout_Three',
            },
        ),
        migrations.CreateModel(
            name='Shoutout_Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', ckeditor.fields.RichTextField()),
                ('Picture', models.ImageField(upload_to='about')),
                ('Name', models.CharField(max_length=50)),
                ('Job_Title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Shoutout_Two',
            },
        ),
    ]
