# Generated by Django 2.1.5 on 2019-11-15 11:33

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', ckeditor.fields.RichTextField()),
                ('Picture_One', models.ImageField(upload_to='footer')),
                ('Picture_Two', models.ImageField(upload_to='footer')),
                ('Picture_Three', models.ImageField(upload_to='footer')),
                ('Picture_Four', models.ImageField(upload_to='footer')),
                ('Picture_Five', models.ImageField(upload_to='footer')),
                ('Picture_Six', models.ImageField(upload_to='footer')),
                ('Picture_Seven', models.ImageField(upload_to='footer')),
                ('Picture_Eight', models.ImageField(upload_to='footer')),
            ],
            options={
                'db_table': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Navigation_Bar_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home', models.CharField(default='home', max_length=50)),
                ('About', models.CharField(default='home', max_length=50)),
                ('Services', models.CharField(default='home', max_length=50)),
                ('Blog', models.CharField(default='home', max_length=50)),
                ('Contact', models.CharField(default='home', max_length=50)),
                ('Careers', models.CharField(default='home', max_length=50)),
            ],
            options={
                'db_table': 'Navigation_Bar_Links',
            },
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Email', models.EmailField(max_length=254)),
                ('Logo', models.ImageField(upload_to='base')),
                ('Icon_Title', models.ImageField(upload_to='base')),
                ('Logo_Icon', models.ImageField(upload_to='base')),
            ],
            options={
                'db_table': 'Others',
            },
        ),
        migrations.CreateModel(
            name='Social_Media_Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.CharField(max_length=50)),
                ('Twitter', models.CharField(max_length=50)),
                ('Instagram', models.CharField(max_length=50)),
                ('Whatsup', models.CharField(max_length=50)),
                ('Telegram', models.CharField(max_length=50)),
                ('LinkedIn', models.CharField(max_length=50)),
                ('Youtube', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Social_Media_Footer',
            },
        ),
    ]
