"""
Django settings for Akilinn project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm&@zk!(5)7v&!wb9-+mkjpu!zg9*_2akpvby+(3^7)ttv5!&kv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # jet dashboard
    'jet.dashboard',
    
    'jet',    
    #  jet dashboard
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ///////THIRD PARTIES INSTALLED/\\\\\\
    # blog
    'django.contrib.sites',
    'django_comments',
    'mptt',
    'tagging',
    'zinnia',
    'compressor',
    'django_prometheus',
    'phonenumber_field',
    'ckeditor',
    #///////// own\\\\\\\\\\\\\\
    'home',
    'about',
    'base',
    'services',
    'contact',
    'errors',
    'agreements',
    'careers',
    'user_data',
]

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware', #cache    
    'django_prometheus.middleware.PrometheusBeforeMiddleware',#prometheus
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',#cache
    'django.contrib.auth.middleware.AuthenticationMiddleware',#two factor authentication
    'django_otp.middleware.OTPMiddleware',#two factor authentication
]

ROOT_URLCONF = 'Akilinn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'zinnia.context_processors.version',#optional
            ],
        },
    },
]

WSGI_APPLICATION = 'Akilinn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#
# 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# caches
CACHES = {
   'default': {
      'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
      'LOCATION': 'Akilinn_site_cache',
   }
}

CACHES = {
   'default': {
      'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
      'LOCATION': '/var/tmp/django_cache',
   }
}
CACHES = {
   'default': {
      'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
      'LOCATION': '127.0.0.1:11211',
   }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Cache key TTL in seconds
CACHE_MIDDLEWARE_SECONDS = 600

# /////////google capcthan   ///////////

RECAPTCHA_PUBLIC_KEY = '6LdfG8EUAAAAACrWPZZdhlUzfI21rHAlxuOxfj-6'
RECAPTCHA_PRIVATE_KEY = '6LdfG8EUAAAAAMXjvnqKsvyayH4EEKSgCPAn46vM'
RECAPTCHA_DOMAIN = 'www.recaptcha.net'# //////blog\\\\\\\
SITE_ID = 1
#
# sentry
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
    dsn="https://0b4e19f27ec0410aa10796da0c3120c9@sentry.io/1813685",
    integrations=[DjangoIntegration()]
)
EMAIL_BACKEND = 'post_office.EmailBackend'

CKEDITOR_UPLOAD_PATH = "media"